mdefault = {}
local mod_path = minetest.get_modpath("mdefault")

dofile(mod_path .. "/fuels.lua")
dofile(mod_path .. "/crafts.lua")
dofile(mod_path .. "/nodes.lua")
dofile(mod_path .. "/craftitems.lua")
dofile(mod_path .. "/saplings.lua")
dofile(mod_path .. "/awards.lua")

dofile(mod_path .. "/materials/iron.lua")
dofile(mod_path .. "/materials/gold.lua")
dofile(mod_path .. "/materials/copper.lua")
dofile(mod_path .. "/materials/zinc.lua")
dofile(mod_path .. "/materials/uranium.lua")
dofile(mod_path .. "/materials/tin.lua")
dofile(mod_path .. "/materials/silver.lua")
dofile(mod_path .. "/materials/platinum.lua")
dofile(mod_path .. "/materials/nickel.lua")
dofile(mod_path .. "/materials/lead.lua")
dofile(mod_path .. "/materials/aluminum.lua")